services:
    #form profile factory
    members.profile.form.factory:
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - '%members_user.profile.form.name%'
            - '%members_user.profile.form.type%'
            - '%members_user.profile.form.validation_groups%'

    #form profile type
    members.profile.form.type:
        class: MembersBundle\Form\Type\ProfileFormType
        arguments:
            - '\MembersBundle\Adapter\User\AbstractUser'
        tags:
            - { name: form.type, alias: members_user_profile }