services:
    MembersBundle\Document\Builder\BrickBuilder:
        shared: false
        arguments:
            - '@security.token_storage'
            - '@Pimcore\Templating\Renderer\IncludeRenderer'
            - '@router'

    MembersBundle\Document\Areabrick\MembersLogin\MembersLogin:
        arguments:
            - '@MembersBundle\Document\Builder\BrickBuilder'
            - '@members.security.login.form.factory'
            - '@translator'
        tags:
            - { name: pimcore.area.brick, id: members_login }