services:

    members.delete_account.form.factory:
        public: true
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - '%members_user.delete_account.form.name%'
            - '%members_user.delete_account.form.type%'
            - '%members_user.delete_account.form.validation_groups%'

    MembersBundle\Form\Type\DeleteAccountFormType:
        arguments:
            - '\MembersBundle\Adapter\User\UserInterface'
        tags:
            - { name: form.type, alias: members_user_delete_account }

    MembersBundle\Controller\DeleteAccountController:
        public: true
        autowire: true
        autoconfigure: true
        arguments:
            $formFactory: '@members.delete_account.form.factory'
