services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # manager: class
    MembersBundle\Manager\ClassManagerInterface: '@MembersBundle\Manager\ClassManager'
    MembersBundle\Manager\ClassManager: ~

    # manager: user
    MembersBundle\Manager\UserManagerInterface: '@MembersBundle\Manager\UserManager'
    MembersBundle\Manager\UserManager: ~

    # manager: restriction
    MembersBundle\Manager\RestrictionManagerInterface: '@MembersBundle\Manager\RestrictionManager'
    MembersBundle\Manager\RestrictionManager: ~

    # manager: login
    MembersBundle\Manager\LoginManagerInterface: '@MembersBundle\Manager\LoginManager'
    MembersBundle\Manager\LoginManager: ~