services:

    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Restriction\RestrictionService: ~

    MembersBundle\Controller\RequestController:
        public: true

    MembersBundle\Controller\Admin\RestrictionController:
        public: true
