pimcore:
    security:
        encoder_factories:
            MembersBundle\Adapter\User\UserInterface: MembersBundle\Security\Encoder\Factory\UserAwareEncoderFactory
    objects:
        class_definitions:
            data:
                map:
                    membersGroupMultiselect: MembersBundle\CoreExtension\GroupMultiselect

security:
    providers:
        members:
            id: MembersBundle\Security\UserProvider
    firewalls:
        members_fe:
            pattern: ^/(?!(admin)).*$
            logout_on_user_change: true
            form_login:
                login_path: members_user_security_login
                check_path: members_user_security_check
                provider: members
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: members_user_security_logout
                invalidate_session: false
                target: /
            anonymous: true
    access_control:
        - { path: ^/_locale/members/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_locale/members/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_locale/members/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

members:
    send_admin_mail_after_register: false
    send_user_mail_after_confirmed: false

    # confirm_by_mail, confirm_by_admin, confirm_instant
    post_register_type: 'confirm_by_mail'

    restriction:
        enabled: false
        allowed_objects: ~
    user:
        adapter:
            class_name: 'MembersUser'
        initial_groups: ~
    group:
        adapter:
            class_name: 'MembersGroup'
    auth:
        adapter:
            class_name: ~
            object_path: ~
    emails:
        default:
            register_confirm: '/email/register-confirm'
            register_confirmed: '/email/register-confirmed'
            register_password_resetting: '/email/password-reset'
            admin_register_notification: '/email/admin-register-notification'
        sites: ~